require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - 'app/channels/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
  NewCops: enable

Rails/Output:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always_true

Style/IfInsideElse:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
